# These settings are generic settings that have to do with your basic esp board configuration. You will figure it out!
esphome:
  name: vemer-adr-r-esphome
  friendly_name: ESPHome Energy Meter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "**********************"

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "**************"
    password: "*******************"

captive_portal:

# Now we start to configure our communication with Modbus.

# First we define the pins on the ESP board, that communicate with the RS485 module...
uart:
  id: mod_bus
  tx_pin: 16   
  rx_pin: 18
  baud_rate: 9600
  debug:

#Now we define that the Modbus library, will use the above configured modbus module
modbus:
  id: modbus1
  uart_id: mod_bus
  send_wait_time: 1500ms

#Now we configure the communication and what addresses to read from the Vemer ADR-R Meter
modbus_controller:
  - id: energymeter
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 5s

#Please note that the adresses, are in HEX format!!!
sensor:
  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "Voltage"
    id: modbus_voltage
    register_type: read
    address: 0x0000
    unit_of_measurement: "V"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "Current Intensity"
    id: modbus_intensity
    register_type: read
    address: 0x0002
    unit_of_measurement: "A"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "Power"
    id: modbus_power
    address: 0x0004
    register_type: read
    unit_of_measurement: "W"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "Apparent Power"
    id: modbus_apparent
    register_type: read
    address: 0x0006
    unit_of_measurement: "VA"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2


  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "Reactive Power Q"
    id: modbus_reactive
    register_type: read
    address: 0x0008
    unit_of_measurement: "var"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "Power Factor"
    id: modbus_pf
    register_type: read
    address: 0xa
    unit_of_measurement: "---"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "Frequency"
    id: modbus_frequency
    register_type: read
    address: 0xc
    unit_of_measurement: "Hz"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "V12"
    id: modbus_v12
    register_type: read
    address: 0xe
    unit_of_measurement: "V"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "V23"
    id: modbus_v23
    register_type: read
    address: 0x10
    unit_of_measurement: "V"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2
  
  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "V31"
    id: modbus_v31
    register_type: read
    address: 0x12
    unit_of_measurement: "V"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "V1"
    id: modbus_v1
    register_type: read
    address: 0x14
    unit_of_measurement: "V"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2
  
  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "V2"
    id: modbus_v2
    register_type: read
    address: 0x16
    unit_of_measurement: "V"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "V3"
    id: modbus_v3
    register_type: read
    address: 0x18
    unit_of_measurement: "V"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "I1"
    id: modbus_i1
    register_type: read
    address: 0x1a
    unit_of_measurement: "A"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "I2"
    id: modbus_i2
    register_type: read
    address: 0x1c
    unit_of_measurement: "A"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "I3"
    id: modbus_i3
    register_type: read
    address: 0x1e
    unit_of_measurement: "A"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2


  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "P1"
    id: modbus_p1
    register_type: read
    address: 0x20
    unit_of_measurement: "W"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "P2"
    id: modbus_p2
    register_type: read
    address: 0x22
    unit_of_measurement: "W"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "P3"
    id: modbus_p3
    register_type: read
    address: 0x24
    unit_of_measurement: "W"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "A1"
    id: modbus_a1
    register_type: read
    address: 0x26
    unit_of_measurement: "VA"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "A2"
    id: modbus_a2
    register_type: read
    address: 0x28
    unit_of_measurement: "VA"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "A3"
    id: modbus_a3
    register_type: read
    address: 0x2a
    unit_of_measurement: "VA"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "Q1"
    id: modbus_q1
    register_type: read
    address: 0x2c
    unit_of_measurement: "var"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "Q2"
    id: modbus_q2
    register_type: read
    address: 0x2e
    unit_of_measurement: "var"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "Q3"
    id: modbus_q3
    register_type: read
    address: 0x0048
    unit_of_measurement: "var"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "PF1"
    id: modbus_pf1
    register_type: read
    address: 0x30
    unit_of_measurement: "---"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "PF2"
    id: modbus_pf2
    register_type: read
    address: 0x34
    unit_of_measurement: "---"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "PF3"
    id: modbus_pf3
    register_type: read
    address: 0x36
    unit_of_measurement: "---"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "φ1"
    id: modbus_fi1
    register_type: read
    address: 0x38
    unit_of_measurement: "o"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "φ2"
    id: modbus_fi2
    register_type: read
    address: 0x3a
    unit_of_measurement: "o"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "φ3"
    id: modbus_fi3
    register_type: read
    address: 0x3c
    unit_of_measurement: "o"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "Ea"
    id: modbus_ea
    register_type: read
    address: 0x3e
    unit_of_measurement: "kW/10"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: energymeter
    name: "Er"
    id: modbus_er
    register_type: read
    address: 0x40
    unit_of_measurement: "kvar/10"
    value_type: FP32
    accuracy_decimals: 2
    register_count: 2
